output_dir: 'www/ui/compressed'
js:
  phonegap_plugins:
    files:
      #- 'ext/phonegap-plugins/iPhone/Badge/Badge.js'
      #- 'ext/phonegap-plugins/iPhone/DatePicker/DatePicker.js'
      #- 'ext/phonegap-plugins/iPhone/LocalNotification/LocalNotification.js'
  global:
    files:
      #- 'www/ui/scripts/weinre.js'
      #- 'www/views/mobile_fix.js'
      #- 'www/ui/scripts/iscroll.js'
      #- 'www/ui/scripts/date.js'
      - 'www/dataproviders/scribble.js'
      - 'www/models/scribble.js'
      - 'www/views/scribblePad.js'
      - 'www/controllers/appController.js'
      - 'www/controllers/scribbleController.js'
      - 'www/controllers/viewAllController.js'
      - 'www/controllers/iAdController.js'
css:
  global:
    files:
      - 'www/ui/stylesheets/common.css'
      - 'www/ui/stylesheets/iphone.css'
